apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-gateway.fullname" . }}
spec:
  selector:
    app: rag-gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
